INSERT INTO instruments (name, slug) VALUES
  ('Guitar', 'guitar'),
  ('Bass', 'bass'),
  ('Drums', 'drums'),
  ('Vocals', 'vocals'),
  ('Keyboard/Piano', 'keyboard'),
  ('Saxophone', 'saxophone'),
  ('Trumpet', 'trumpet'),
  ('Trombone', 'trombone'),
  ('Violin', 'violin'),
  ('Cello', 'cello'),
  ('Flute', 'flute'),
  ('Harmonica', 'harmonica'),
  ('DJ/Turntables', 'dj'),
  ('Banjo', 'banjo'),
  ('Mandolin', 'mandolin'),
  ('Ukulele', 'ukulele'),
  ('Steel Guitar', 'steel-guitar'),
  ('Fiddle', 'fiddle'),
  ('Sound Engineer', 'sound-engineer'),
  ('Other', 'other');

INSERT INTO genres (name, slug) VALUES
  ('Rock', 'rock'),
  ('Jazz', 'jazz'),
  ('Blues', 'blues'),
  ('Country', 'country'),
  ('R&B/Soul', 'rnb-soul'),
  ('Pop', 'pop'),
  ('Folk', 'folk'),
  ('Classical', 'classical'),
  ('Hip Hop', 'hip-hop'),
  ('Electronic', 'electronic'),
  ('Funk', 'funk'),
  ('Reggae', 'reggae'),
  ('Latin', 'latin'),
  ('Gospel', 'gospel'),
  ('Bluegrass', 'bluegrass'),
  ('Contemporary', 'contemporary'),
  ('Indie', 'indie'),
  ('Metal', 'metal'),
  ('Punk', 'punk'),
  ('World', 'world'),
  ('Cover Band', 'cover-band'),
  ('Wedding/Event', 'wedding-event'),
  ('Other', 'other');
